an_najah_organizer/room/urls.py
from django.urls import path
from .views import create_room_view
from .views import update_room_view

app_name = "rooms"
urlpatterns = [
    path("", create_room_view, name="fill"),
    path("edit/<int:room_id>/", update_room_view, name="edit"),
]

an_najah_organizer/users/urls.py
from django.urls import path, include

from .views import user_detail_view
from .views import user_redirect_view
from .views import user_update_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),

]

config/urls.py
# ruff: noqa
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from an_najah_organizer.room.views import room_table

urlpatterns = [
    path("", room_table, name="home"),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("an_najah_organizer.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    # ...
    ##
    path("fill/", include("an_najah_organizer.room.urls", namespace="rooms")),
    # Media files
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
]


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

an_najah_organizer/maps/models.py
from django.db import models

# Create your models here.

an_najah_organizer/room/forms.py
from django.forms import ModelForm
from django import forms
from .models import RoomDetails
from .models import Room
from .models import Building
from .models import Floor
from .models import RoomItems
from django.forms import modelformset_factory

"""

class CampusForm(forms.Form):
    campus = forms.ModelChoiceField(
        queryset=Campus.objects.all(),
        empty_label=None,
        label="Where Are You At?",

    )
"""


class BuildingForm(forms.Form):
    building = forms.ModelChoiceField(
        queryset=Building.objects.all(),
        empty_label=None,
        label="",
        widget=forms.Select(
            attrs={
                "class": "border rounded px-4 py-2 w-full shadow-md",
                "placeholder": "floor number",
            }
        ),
    )


class FloorForm(ModelForm):
    class Meta:
        model = Floor
        fields = ["floor_number"]
        labels = {"floor_number": "Floor Number"}
        widgets = {
            "floor_number": forms.TextInput(
                attrs={
                    "class": "border rounded px-4 py-2 w-full shadow-md",
                    "placeholder": "floor number",
                }
            ),
        }


class RoomForm(ModelForm):
    class Meta:
        model = Room
        fields = [
            "room_number",
            "width",
            "height",
            "length",
            "usage",
            "x",
            "y",
        ]
        labels = {"room_number": "Room Number", "usage": "Usage"}
        widgets = {
            "room_number": forms.TextInput(
                attrs={
                    "class": "border rounded px-4 py-2 w-full shadow-md",
                    "placeholder": "room number",
                }
            ),
            "width": forms.TextInput(
                attrs={
                    "class": "border rounded px-4 py-2 w-full shadow-md",
                    "placeholder": "Width",
                }
            ),
            "height": forms.TextInput(
                attrs={
                    "class": "border rounded px-4 py-2 w-full shadow-md ",
                    "placeholder": "Height",
                }
            ),
            "length": forms.TextInput(
                attrs={
                    "class": "border rounded px-4 py-2 w-full shadow-md",
                    "placeholder": "Length",
                }
            ),
            "usage": forms.TextInput(
                attrs={
                    "class": "border rounded px-4 py-2 w-full shadow-md",
                    "placeholder": "Usage",
                }
            ),
            "x": forms.NumberInput(
                attrs={
                    "class": "border rounded px-4 py-2 w-full shadow-md",
                    "placeholder": "X",
                }
            ),
            "y": forms.NumberInput(
                attrs={
                    "class": "border rounded px-4 py-2 w-full shadow-md",
                    "placeholder": "Y",
                }
            ),
        }


class RoomDetailsForm(ModelForm):
    class Meta:
        model = RoomDetails
        fields = ["item", "amount", "model", "attachments", "notes"]
        labels = {
            "item": "Item",
            "amount": "Amount",
            "model": "Model",
            "attachments": "Attachments",
            "notes": "Notes",
        }
        widgets = {
            "item": forms.Select(
                choices=RoomItems.objects.all(),
                attrs={
                    "class": "border rounded px-4 py-2 w-full shadow-md",
                    "placeholder": "Item",
                },
            ),
            "amount": forms.NumberInput(
                attrs={
                    "class": "border rounded px-4 py-2 w-full shadow-md",
                    "placeholder": "Amount",
                }
            ),
            "model": forms.TextInput(
                attrs={
                    "class": "border rounded px-4 py-2 w-full shadow-md",
                    "placeholder": "Model",
                }
            ),
            "attachments": forms.TextInput(
                attrs={
                    "class": "border rounded px-4 py-2 w-full shadow-md",
                    "placeholder": "Attachments",
                }
            ),
            "notes": forms.Textarea(
                attrs={
                    "class": "border rounded px-4 py-2 w-full shadow-md",
                    "placeholder": "Notes",
                }
            ),
        }


RoomDetailsFormSet = modelformset_factory(
    RoomDetails, form=RoomDetailsForm, extra=1
)  # extra defines new empty forms

RoomDetailsFormSetUpdate = modelformset_factory(
    RoomDetails, form=RoomDetailsForm, extra=0
)  # extra defines new empty forms

an_najah_organizer/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.utils.translation import gettext_lazy as _

from .models import User


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):  # type: ignore[name-defined]
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):  # type: ignore[name-defined]
        model = User
        error_messages = {
            "username": {"unique": _("This username has already been taken.")},
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

an_najah_organizer/maps/views.py
from django.shortcuts import render


# Create your views here.
def map_view(request):
    return render(request, "maps/map.html", {})

an_najah_organizer/room/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic.edit import CreateView
from .models import Campus
from .models import Media
from .forms import BuildingForm
from .forms import FloorForm
from .forms import RoomForm
from .forms import RoomDetailsForm
from .forms import RoomDetailsFormSetUpdate
from .forms import RoomDetailsFormSet
from .models import Room
from .models import RoomDetails
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404


def room_table(request):
    if request.user.is_authenticated:
        rooms = (
            Room.objects.filter(user=request.user)
            .order_by("-created_at")[0:5]
            .prefetch_related()
        )
        return render(request, "pages/home.html", {"rooms": rooms})
    return render(request, "pages/home.html", {})


@login_required
def update_room_view(request, room_id):

    room_instance = get_object_or_404(Room, id=room_id)
    campuses = Campus.objects.all()

    building_form = BuildingForm()
    floor_form = FloorForm(instance=room_instance.floor)
    room_form = RoomForm(instance=room_instance)

    detail_form = RoomDetailsFormSetUpdate(
        queryset=RoomDetails.objects.filter(room=room_instance)
    )

    images = Media.objects.filter(room=room_instance)
    print(RoomDetails.objects.filter(room=room_instance))
    print(RoomDetails.objects.all())
    if request.method == "POST":
        # selected_campus_id = request.POST.get('selected_campus')
        building_form = BuildingForm(request.POST)
        floor_form = FloorForm(request.POST)
        room_form = RoomForm(request.POST)
        detail_form = RoomDetailsForm(request.POST)
        print(detail_form)
        if building_form.is_valid():
            building_data = building_form.cleaned_data

            selected_building = building_data.get("building")
            selected_campus_id = selected_building.campus
            if floor_form.is_valid():
                floor_instance = floor_form.save(commit=False)
                floor_instance.building = selected_building

                if room_form.is_valid():
                    room_instance = room_form.save(commit=False)
                    room_instance.campus = selected_campus_id
                    room_instance.building = selected_building
                    room_instance.floor = floor_instance
                    room_instance.user = request.user

                    floor_form.save()
                    room_instance.save()
                    images = request.FILES.getlist("cs")
                    for image in images:
                        Media.objects.create(room=room_instance, image=image)

                    if detail_form.is_valid():
                        detail_instance = detail_form.save(commit=False)
                        if detail_instance.amount and detail_instance.amount > 0:
                            detail_instance.room = room_instance
                            detail_instance.save()

                    return redirect(reverse("home"))

                else:
                    print("Room form errors:", room_form.errors)

            else:
                print("Floor form errors:", floor_form.errors)

        else:
            print("Building form errors:", building_form.errors)
    print("images", images)
    return render(
        request,
        "rooms/fill_room.html",
        {
            "campuses": campuses,
            "buildings": building_form,
            "floor_form": floor_form,
            "room_form": room_form,
            "detail_form": detail_form,
            "images": images,
        },
    )


@login_required
def create_room_view(request):
    # Initialize the forms
    campuses = Campus.objects.all()
    building_form = BuildingForm()
    floor_form = FloorForm()
    room_form = RoomForm()
    detail_form = RoomDetailsFormSet(queryset=RoomDetails.objects.none())
    print(detail_form)
    if request.method == "POST":
        # selected_campus_id = request.POST.get('selected_campus')
        building_form = BuildingForm(request.POST)
        floor_form = FloorForm(request.POST)
        room_form = RoomForm(request.POST)
        detail_form = RoomDetailsFormSet(
            request.POST
        )  # Populate formset with POST data

        if building_form.is_valid():
            building_data = building_form.cleaned_data

            selected_building = building_data.get("building")
            selected_campus_id = selected_building.campus
            print("selected_campus_id", selected_campus_id)
            if floor_form.is_valid():
                floor_instance = floor_form.save(commit=False)
                floor_instance.building = selected_building

                if room_form.is_valid():
                    room_instance = room_form.save(commit=False)
                    room_instance.campus = selected_campus_id
                    room_instance.building = selected_building
                    room_instance.floor = floor_instance
                    room_instance.user = request.user

                    floor_form.save()
                    room_instance.save()
                    images = request.FILES.getlist("cs")[1:]
                    for image in images:
                        Media.objects.create(room=room_instance, image=image)

                    if detail_form.is_valid():
                        for form in detail_form:
                            print("formm", form)
                            if form.cleaned_data:
                                detail_instance = form.save(commit=False)
                                if (
                                    detail_instance.amount
                                    and detail_instance.amount > 0
                                ):
                                    detail_instance.room = room_instance
                                    detail_instance.save()

                        print("detail_form", detail_form)

                        return redirect(reverse("home"))

                    else:
                        print("detail_form ERROR", detail_form.errors)

                else:
                    print("Room form errors:", room_form.errors)

            else:
                print("Floor form errors:", floor_form.errors)

        else:
            print("Building form errors:", building_form.errors)

    return render(
        request,
        "rooms/fill_room.html",
        {
            "campuses": campuses,
            "buildings": building_form,
            "floor_form": floor_form,
            "room_form": room_form,
            "detail_form": detail_form,
        },
    )

an_najah_organizer/users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import QuerySet
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView
from django.views.generic import RedirectView
from django.views.generic import UpdateView

from an_najah_organizer.users.models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self) -> str:
        assert self.request.user.is_authenticated  # type guard
        return self.request.user.get_absolute_url()

    def get_object(self, queryset: QuerySet | None=None) -> User:
        assert self.request.user.is_authenticated  # type guard
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self) -> str:
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

an_najah_organizer/templates/pages/about.html
{% extends "_base.html" %}

an_najah_organizer/templates/pages/home.html
{% extends '_base.html' %}
{% block content %}
  <div class="bg-white">
    <header class="absolute inset-x-0 top-0 z-50">
      <nav class="flex items-center justify-between p-6 lg:px-8" aria-label="Global">
        <div class="flex lg:flex-1">
          <a href="#" class="-m-1.5 p-1.5">
            <span class="sr-only">Your Company</span>
            <img class="h-8 w-auto" src="https://tailwindui.com/plus/img/logos/mark.svg?color=indigo&shade=600" alt="" />
          </a>

          {% if user.is_authenticated %}
            {{ user.username }}
          {% endif %}
        </div>
        <div class="flex lg:hidden">
          <button type="button" class="-m-2.5 inline-flex items-center justify-center rounded-md p-2.5 text-gray-700">
            <span class="sr-only">Open main menu</span>
            <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true" data-slot="icon">
              <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
            </svg>
          </button>
        </div>
        <div class="hidden lg:flex lg:gap-x-12">
          <a href="#" class="text-sm font-semibold leading-6 text-gray-900">Product</a>
          <a href="#" class="text-sm font-semibold leading-6 text-gray-900">Features</a>
          <a href="#" class="text-sm font-semibold leading-6 text-gray-900">Marketplace</a>
          <a href="#" class="text-sm font-semibold leading-6 text-gray-900">Company</a>
        </div>
        <div class="hidden lg:flex lg:flex-1 lg:justify-end">
          {% if user.is_authenticated %}
            <a href="accounts/logout" class="text-sm font-semibold leading-6 text-gray-900">Log out <span aria-hidden="true">&rarr;</span></a>
          {% else %}
            <a href="accounts/signup" class="text-sm font-semibold leading-6 text-gray-900">Sign up <span aria-hidden="true"></span></a>
          {% endif %}
        </div>
      </nav>
      <!-- Mobile menu, show/hide based on menu open state. -->
      <div class="lg:hidden" role="dialog" aria-modal="true">
        <!-- Background backdrop, show/hide based on slide-over state. -->
        <div class="fixed inset-0 z-50"></div>
        <div class="fixed inset-y-0 right-0 z-50 w-full overflow-y-auto bg-white px-6 py-6 sm:max-w-sm sm:ring-1 sm:ring-gray-900/10">
          <div class="flex items-center justify-between">
            <a href="#" class="-m-1.5 p-1.5">
              <span class="sr-only">Your Company</span>
              <img class="h-8 w-auto" src="https://tailwindui.com/plus/img/logos/mark.svg?color=indigo&shade=600" alt="" />
            </a>
            <button type="button" class="-m-2.5 rounded-md p-2.5 text-gray-700">
              <span class="sr-only">Close menu</span>
              <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true" data-slot="icon">
                <path stroke-linecap="round" stroke-linejoin="round" d="M6 18 18 6M6 6l12 12" />
              </svg>
            </button>
          </div>
          <div class="mt-6 flow-root">
            <div class="-my-6 divide-y divide-gray-500/10">
              <div class="space-y-2 py-6">
                <a href="#" class="-mx-3 block rounded-lg px-3 py-2 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-50">Product</a>
                <a href="#" class="-mx-3 block rounded-lg px-3 py-2 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-50">Features</a>
                <a href="#" class="-mx-3 block rounded-lg px-3 py-2 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-50">Marketplace</a>
                <a href="#" class="-mx-3 block rounded-lg px-3 py-2 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-50">Company</a>
              </div>
              <div class="py-6">
                <a href="#" class="-mx-3 block rounded-lg px-3 py-2.5 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-50">Log in</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </header>

    <div class="relative isolate px-6 pt-14 lg:px-8">
      <div class="absolute inset-x-0 -top-40 -z-10 transform-gpu overflow-hidden blur-3xl sm:-top-80" aria-hidden="true">
        <div class="relative left-[calc(50%-11rem)] aspect-[1155/678] w-[36.125rem] -translate-x-1/2 rotate-[30deg] bg-gradient-to-tr from-[#ff80b5] to-[#9089fc] opacity-30 sm:left-[calc(50%-30rem)] sm:w-[72.1875rem]" style="
                clip-path: polygon(
                    74.1% 44.1%,
                    100% 61.6%,
                    97.5% 26.9%,
                    85.5% 0.1%,
                    80.7% 2%,
                    72.5% 32.5%,
                    60.2% 62.4%,
                    52.4% 68.1%,
                    47.5% 58.3%,
                    45.2% 34.5%,
                    27.5% 76.7%,
                    0.1% 64.9%,
                    17.9% 100%,
                    27.6% 76.8%,
                    76.1% 97.7%,
                    74.1% 44.1%
                );
                "></div>
      </div>
      <div class="mx-auto max-w-2xl py-16">
        <div class="text-center">
          <h1 class="text-balance text-5xl font-semibold tracking-tight text-gray-900 sm:text-7xl">Data to enrich the University</h1>
          <div class="hidden sm:mb-8 sm:flex sm:justify-center mt-5">
            <div class="relative rounded-full px-3 py-1 text-sm leading-6 text-gray-600 ring-1 ring-gray-900/10 hover:ring-gray-900/20">
              Announcing our next round of funding.
              <a href="#" class="font-semibold text-indigo-600">
                <span class="absolute inset-0" aria-hidden="true"></span>Read more
                <span aria-hidden="true">&rarr;</span>
              </a>
            </div>
          </div>
          <p class="mt-8 text-pretty text-lg font-medium text-gray-500 sm:text-xl/8">Anim aute id magna aliqua ad ad non deserunt sunt. Qui irure qui lorem cupidatat commodo. Elit sunt amet fugiat veniam occaecat.</p>

          <div class="mt-10 flex items-center justify-center gap-x-6">
            <a href="{% url 'rooms:fill' %}" class="rounded-md bg-indigo-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Add New Room</a>
            <a href="#" class="text-sm font-semibold leading-6 text-gray-900">Learn more <span aria-hidden="true">→</span></a>
          </div>
        </div>
      </div>

      {% if rooms %}
        {% include '../fragment/table.html' %}
      {% endif %}
      <div class="absolute inset-x-0 top-[calc(100%-13rem)] -z-10 transform-gpu overflow-hidden blur-3xl sm:top-[calc(100%-30rem)]" aria-hidden="true">
        <div class="relative left-[calc(50%+3rem)] aspect-[1155/678] w-[36.125rem] -translate-x-1/2 bg-gradient-to-tr from-[#ff80b5] to-[#9089fc] opacity-30 sm:left-[calc(50%+36rem)] sm:w-[72.1875rem]" style="
                clip-path: polygon(
                    74.1% 44.1%,
                    100% 61.6%,
                    97.5% 26.9%,
                    85.5% 0.1%,
                    80.7% 2%,
                    72.5% 32.5%,
                    60.2% 62.4%,
                    52.4% 68.1%,
                    47.5% 58.3%,
                    45.2% 34.5%,
                    27.5% 76.7%,
                    0.1% 64.9%,
                    17.9% 100%,
                    27.6% 76.8%,
                    76.1% 97.7%,
                    74.1% 44.1%
                );
                "></div>
      </div>
    </div>
  </div>
{% endblock %}